variables:
  MAVEN_CLI_OPTS: "-s ./settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  
stages:
  - build
  - test
  - deploy

.maven-build:
  image: maven:3-jdk-11
  stage: build
  cache:
    paths:
      - .m2/
      
build:
  extends: .maven-build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - ./target
  when: always
  
test:
  tags:
    - docker
  extends: .maven-build
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
