sudo: false
language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "collonville-tom-sonar"
    token:
      secure: SONAR_TOKEN

before_install: true
install : true
before_script : true

script: 
  - cp settings.xml $HOME/.m2/settings.xml 
  - mvn install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
