sudo: false
language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "collonville-tom-sonar"
    token:
      secure: "cd3f317b2dc0418833b75ccdd44d3303c953da8b"

before_install: true
install : true
before_script : true

script: 
  - cp settings.xml $HOME/.m2/settings.xml 
  - mvn clean install
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
